# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn --verbose
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn bootstrap
      - run: yarn build
      # don't rely on <sym>links in container mode--just move the files to more
      # closely mimic production
      - run: rm -rf packages/api/static/public && mkdir -p packages/api/static && cp -r packages/ui/build packages/api/static/public
      - run: yarn test

